using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb.Storage;

namespace TransactionDemo.Entities;

/// <summary>
/// Table class for managing accounts and transaction records in DynamoDB.
/// 
/// This class demonstrates single-table design where accounts and their
/// transaction records share the same table, using hierarchical composite
/// keys to enable efficient access patterns.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Key Design:</strong>
/// </para>
/// <para>
/// All entities use the same partition key format "ACCOUNT#{accountId}" to group
/// all data for an account together. The sort key distinguishes entity types:
/// </para>
/// <list type="bullet">
/// <item><description>Account: sk = "PROFILE"</description></item>
/// <item><description>Transaction: sk = "TXN#{timestamp}#{txnId}"</description></item>
/// </list>
/// <para>
/// <strong>Access Patterns:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Get account profile: Query pk = "ACCOUNT#{id}", sk = "PROFILE"</description></item>
/// <item><description>Get account transactions: Query pk = "ACCOUNT#{id}", sk begins_with "TXN#"</description></item>
/// </list>
/// </remarks>
public partial class TransactionDemoTable : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for transaction demo.
    /// </summary>
    public const string TableName = "transaction-demo";

    /// <summary>
    /// Initializes a new instance of the TransactionDemoTable class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public TransactionDemoTable(IAmazonDynamoDB client) : this(client, TableName)
    {
    }

    // Entity accessors (Accounts, Transactions) are generated by the source generator
    // based on the [GenerateEntityProperty] attributes on Account and TransactionRecord entities.
}
