using System.Text;

namespace Oproto.FluentDynamoDb.SourceGenerator.Generators;

/// <summary>
/// Generates consistent file headers for all generated source files.
/// </summary>
internal static class FileHeaderGenerator
{
    /// <summary>
    /// The version of the source generator.
    /// This should be updated when significant changes are made to the generator.
    /// </summary>
    private const string GeneratorVersion = "1.0.0";

    /// <summary>
    /// Generates a standard file header with auto-generated marker, nullable directive,
    /// timestamp, and version information.
    /// </summary>
    /// <param name="sb">The StringBuilder to append the header to.</param>
    public static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This code was generated by the Oproto.FluentDynamoDb Source Generator.");
        sb.AppendLine($"// Generator Version: {GeneratorVersion}");
        sb.AppendLine($"// Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// Changes to this file may be lost when the code is regenerated.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a file header as a string.
    /// </summary>
    /// <returns>The generated file header.</returns>
    public static string GenerateFileHeaderString()
    {
        var sb = new StringBuilder();
        GenerateFileHeader(sb);
        return sb.ToString();
    }
}
