using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb.Storage;

namespace FluentDynamoDb.OperationSamples.Models;

/// <summary>
/// Table class for managing orders and order lines in DynamoDB.
/// 
/// This class demonstrates single-table design where multiple entity types share
/// the same table, using composite keys to enable efficient access patterns.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Key Design:</strong>
/// </para>
/// <para>
/// All entities use the partition key format "ORDER#{orderId}" to group
/// all data for an order together. The sort key distinguishes entity types:
/// </para>
/// <list type="bullet">
/// <item><description>Order: sk = "META"</description></item>
/// <item><description>OrderLine: sk = "LINE#{lineId}"</description></item>
/// </list>
/// <para>
/// <strong>Access Patterns:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Get order: Query pk = "ORDER#{orderId}", sk = "META"</description></item>
/// <item><description>Get order lines: Query pk = "ORDER#{orderId}", sk begins_with "LINE#"</description></item>
/// <item><description>Get complete order: Query pk = "ORDER#{orderId}" (returns both order and lines)</description></item>
/// </list>
/// </remarks>
public partial class OrdersTable : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for orders.
    /// </summary>
    public const string TableName = "Orders";

    /// <summary>
    /// Initializes a new instance of the OrdersTable class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
#pragma warning disable CS8618 // Non-nullable property must contain a non-null value - Properties are initialized by source generator
    public OrdersTable(IAmazonDynamoDB client) : base(client, TableName)
    {
    }
#pragma warning restore CS8618

    // Entity accessors (Orders, OrderLines) are generated by the source generator
    // based on the [GenerateEntityProperty] attributes on Order and OrderLine entities.
}
