using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb;
using Oproto.FluentDynamoDb.Geospatial;
using Oproto.FluentDynamoDb.Storage;

namespace StoreLocator.Entities;

/// <summary>
/// Table class for managing stores indexed with Google's S2 geometry library.
/// Implements adaptive precision selection based on search radius.
/// 
/// This is a minimal partial class that relies on source-generated entity accessors
/// and spatial query extensions. The source generator creates:
/// - Stores property (entity accessor) from [GenerateEntityProperty(Name = "Stores")]
/// - S2IndexFine property (index accessor) from [GlobalSecondaryIndex("s2-index-fine")]
/// - S2IndexMedium property (index accessor) from [GlobalSecondaryIndex("s2-index-medium")]
/// - S2IndexCoarse property (index accessor) from [GlobalSecondaryIndex("s2-index-coarse")]
/// </summary>
/// <remarks>
/// <para>
/// <strong>Multi-Precision Strategy:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Fine (Level 14, ~284m): For radius ≤ 2km</description></item>
/// <item><description>Medium (Level 12, ~1.1km): For radius 2-10km</description></item>
/// <item><description>Coarse (Level 10, ~4.5km): For radius > 10km</description></item>
/// </list>
/// </remarks>
public partial class StoresS2Table : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for S2-indexed stores.
    /// </summary>
    public const string TableName = "stores-s2";

    /// <summary>
    /// Initializes a new instance of the StoresS2Table class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public StoresS2Table(IAmazonDynamoDB client) 
        : this(client, TableName, new FluentDynamoDbOptions().AddGeospatial())
    {
    }

    // Entity accessor (Stores) is generated by the source generator
    // based on the [GenerateEntityProperty(Name = "Stores")] attribute on StoreS2 entity.
    //
    // Index accessors are generated by the source generator based on the
    // [GlobalSecondaryIndex] attributes on StoreS2 location properties:
    // - S2IndexFine (s2-index-fine): Level 14, ~284m cells for radius ≤ 2km
    // - S2IndexMedium (s2-index-medium): Level 12, ~1.1km cells for radius 2-10km
    // - S2IndexCoarse (s2-index-coarse): Level 10, ~4.5km cells for radius > 10km

    /// <summary>
    /// Selects the appropriate S2 level based on search radius.
    /// </summary>
    /// <param name="radiusKilometers">The search radius in kilometers.</param>
    /// <returns>The S2 level to use for the query.</returns>
    public static int SelectS2Level(double radiusKilometers)
    {
        return radiusKilometers switch
        {
            <= 2.0 => 14,
            <= 10.0 => 12,
            _ => 10
        };
    }
}
