using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb;
using Oproto.FluentDynamoDb.Geospatial;
using Oproto.FluentDynamoDb.Storage;

namespace StoreLocator.Entities;

/// <summary>
/// Table class for managing stores indexed with Uber's H3 hexagonal spatial index.
/// Implements adaptive precision selection based on search radius.
/// 
/// This is a minimal partial class that relies on source-generated entity accessors
/// and spatial query extensions. The source generator creates:
/// - Stores property (entity accessor) from [GenerateEntityProperty(Name = "Stores")]
/// - H3IndexFine property (index accessor) from [GlobalSecondaryIndex("h3-index-fine")]
/// - H3IndexMedium property (index accessor) from [GlobalSecondaryIndex("h3-index-medium")]
/// - H3IndexCoarse property (index accessor) from [GlobalSecondaryIndex("h3-index-coarse")]
/// </summary>
/// <remarks>
/// <para>
/// <strong>Multi-Precision Strategy:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Fine (Resolution 9, ~174m): For radius ≤ 2km</description></item>
/// <item><description>Medium (Resolution 7, ~1.2km): For radius 2-10km</description></item>
/// <item><description>Coarse (Resolution 5, ~8.5km): For radius > 10km</description></item>
/// </list>
/// </remarks>
public partial class StoresH3Table : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for H3-indexed stores.
    /// </summary>
    public const string TableName = "stores-h3";

    /// <summary>
    /// Initializes a new instance of the StoresH3Table class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public StoresH3Table(IAmazonDynamoDB client) 
        : this(client, TableName, new FluentDynamoDbOptions().AddGeospatial())
    {
    }

    // Entity accessor (Stores) is generated by the source generator
    // based on the [GenerateEntityProperty(Name = "Stores")] attribute on StoreH3 entity.
    //
    // Index accessors are generated by the source generator based on the
    // [GlobalSecondaryIndex] attributes on StoreH3 location properties:
    // - H3IndexFine (h3-index-fine): Resolution 9, ~174m cells for radius ≤ 2km
    // - H3IndexMedium (h3-index-medium): Resolution 7, ~1.2km cells for radius 2-10km
    // - H3IndexCoarse (h3-index-coarse): Resolution 5, ~8.5km cells for radius > 10km

    /// <summary>
    /// Selects the appropriate H3 resolution based on search radius.
    /// </summary>
    /// <param name="radiusKilometers">The search radius in kilometers.</param>
    /// <returns>The H3 resolution to use for the query.</returns>
    public static int SelectH3Resolution(double radiusKilometers)
    {
        return radiusKilometers switch
        {
            <= 2.0 => 9,
            <= 10.0 => 7,
            _ => 5
        };
    }
}
