using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb;
using Oproto.FluentDynamoDb.Geospatial;
using Oproto.FluentDynamoDb.Storage;

namespace StoreLocator.Entities;

/// <summary>
/// Table class for managing stores indexed with GeoHash spatial encoding.
/// 
/// This is a minimal partial class that relies on source-generated entity accessors
/// and spatial query extensions. The source generator creates:
/// - Stores property (entity accessor) from [GenerateEntityProperty(Name = "Stores")]
/// - GeohashIndex property (index accessor) from [GlobalSecondaryIndex("geohash-index")]
/// </summary>
public partial class StoresGeohashTable : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for GeoHash-indexed stores.
    /// </summary>
    public const string TableName = "stores-geohash";

    /// <summary>
    /// Initializes a new instance of the StoresGeohashTable class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public StoresGeohashTable(IAmazonDynamoDB client) 
        : this(client, TableName, new FluentDynamoDbOptions().AddGeospatial())
    {
    }

    // Entity accessor (Stores) is generated by the source generator
    // based on the [GenerateEntityProperty(Name = "Stores")] attribute on StoreGeoHash entity.
    //
    // Index accessor (GeohashIndex) is generated by the source generator
    // based on the [GlobalSecondaryIndex("geohash-index")] attribute on StoreGeoHash.Location.
}
