using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Oproto.FluentDynamoDb.SourceGenerator;
using Oproto.FluentDynamoDb.SourceGenerator.UnitTests.TestHelpers;
using Oproto.FluentDynamoDb.SourceGenerator.UnitTests.Integration;

namespace Oproto.FluentDynamoDb.SourceGenerator.UnitTests.Generators;

/// <summary>
/// Unit tests for nested UpdateModel generation for properties with [DynamoDbMap] attribute
/// where the property type has [DynamoDbEntity] attribute.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Generator", "NestedUpdateModel")]
public class NestedUpdateModelGeneratorTests
{
    [Fact]
    public void Generator_WithNestedMapProperty_GeneratesNestedUpdateModelClass()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Address
    {
        [DynamoDbAttribute(""street"")]
        public string Street { get; set; } = string.Empty;
        
        [DynamoDbAttribute(""city"")]
        public string City { get; set; } = string.Empty;
        
        [DynamoDbAttribute(""zipCode"")]
        public string ZipCode { get; set; } = string.Empty;
    }

    [DynamoDbTable(""customers"")]
    public partial class Customer
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbAttribute(""name"")]
        public string Name { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""address"")]
        public Address ShippingAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        // Verify nested UpdateModel class is generated by the main generator (for [DynamoDbEntity] types)
        var nestedUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("AddressUpdateModel.g.cs"));
        
        nestedUpdateModelFile.Should().NotBeNull("should generate AddressUpdateModel class");
        
        var code = nestedUpdateModelFile!.SourceText.ToString();
        
        // Verify class structure
        code.ShouldContainClass("AddressUpdateModel");
        code.Should().Contain("namespace TestNamespace", "should preserve entity namespace");
        
        // Verify properties with nullable types
        code.Should().Contain("string? Street", "should generate nullable string for Street property");
        code.Should().Contain("string? City", "should generate nullable string for City property");
        code.Should().Contain("string? ZipCode", "should generate nullable string for ZipCode property");
        
        // Verify XML documentation
        code.Should().Contain("/// <summary>", "should include XML documentation");
    }

    [Fact]
    public void Generator_WithNestedMapProperty_ParentUpdateModelUsesNestedType()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Address
    {
        [DynamoDbAttribute(""city"")]
        public string City { get; set; } = string.Empty;
    }

    [DynamoDbTable(""customers"")]
    public partial class Customer
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""address"")]
        public Address ShippingAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        // Verify parent UpdateModel uses nested UpdateModel type
        var parentUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("CustomerUpdateModel.g.cs"));
        
        parentUpdateModelFile.Should().NotBeNull("should generate CustomerUpdateModel class");
        
        var code = parentUpdateModelFile!.SourceText.ToString();
        
        // Verify ShippingAddress property uses AddressUpdateModel type
        code.Should().Contain("AddressUpdateModel? ShippingAddress", 
            "should use AddressUpdateModel type for nested map property");
        
        // Verify documentation mentions nested update
        code.Should().Contain("Use AddressUpdateModel to partially update nested properties",
            "should document nested update usage");
    }

    [Fact]
    public void Generator_WithMultiLevelNesting_GeneratesAllNestedUpdateModels()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Country
    {
        [DynamoDbAttribute(""code"")]
        public string Code { get; set; } = string.Empty;
        
        [DynamoDbAttribute(""name"")]
        public string Name { get; set; } = string.Empty;
    }

    [DynamoDbEntity]
    public partial class Address
    {
        [DynamoDbAttribute(""city"")]
        public string City { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""country"")]
        public Country Country { get; set; } = new();
    }

    [DynamoDbTable(""orders"")]
    public partial class Order
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""shippingAddress"")]
        public Address ShippingAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        // Verify CountryUpdateModel is generated
        var countryUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("CountryUpdateModel.g.cs"));
        
        countryUpdateModelFile.Should().NotBeNull("should generate CountryUpdateModel class");
        
        var countryCode = countryUpdateModelFile!.SourceText.ToString();
        countryCode.Should().Contain("string? Code", "should generate nullable string for Code property");
        countryCode.Should().Contain("string? Name", "should generate nullable string for Name property");
        
        // Verify AddressUpdateModel is generated with nested CountryUpdateModel
        var addressUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("AddressUpdateModel.g.cs"));
        
        addressUpdateModelFile.Should().NotBeNull("should generate AddressUpdateModel class");
        
        var addressCode = addressUpdateModelFile!.SourceText.ToString();
        addressCode.Should().Contain("string? City", "should generate nullable string for City property");
        addressCode.Should().Contain("CountryUpdateModel? Country", 
            "should use CountryUpdateModel type for nested Country property");
        
        // Verify OrderUpdateModel uses AddressUpdateModel
        var orderUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("OrderUpdateModel.g.cs"));
        
        orderUpdateModelFile.Should().NotBeNull("should generate OrderUpdateModel class");
        
        var orderCode = orderUpdateModelFile!.SourceText.ToString();
        orderCode.Should().Contain("AddressUpdateModel? ShippingAddress",
            "should use AddressUpdateModel type for ShippingAddress property");
    }

    [Fact]
    public void Generator_WithDictionaryProperty_DoesNotGenerateNestedUpdateModel()
    {
        // Arrange
        var source = @"
using System;
using System.Collections.Generic;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbTable(""items"")]
    public partial class Item
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""metadata"")]
        public Dictionary<string, string> Metadata { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        // Verify no nested UpdateModel is generated for Dictionary
        var nestedUpdateModelFiles = result.GeneratedSources
            .Where(s => s.FileName.Contains("UpdateModel.g.cs") && 
                       !s.FileName.Contains("ItemUpdateModel.g.cs"));
        
        nestedUpdateModelFiles.Should().BeEmpty(
            "should not generate nested UpdateModel for Dictionary types");
        
        // Verify ItemUpdateModel uses Dictionary type directly
        var itemUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("ItemUpdateModel.g.cs"));
        
        itemUpdateModelFile.Should().NotBeNull();
        var code = itemUpdateModelFile!.SourceText.ToString();
        code.Should().Contain("Dictionary<string, string>? Metadata",
            "should use Dictionary type directly for Dictionary properties");
    }

    [Fact]
    public void Generator_WithoutDynamoDbEntityAttribute_DoesNotGenerateNestedUpdateModel()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    // Note: No [DynamoDbEntity] attribute
    public class Address
    {
        public string City { get; set; } = string.Empty;
    }

    [DynamoDbTable(""customers"")]
    public partial class Customer
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""address"")]
        public Address ShippingAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert - Should have a diagnostic warning about missing [DynamoDbEntity]
        // but should not generate nested UpdateModel
        var nestedUpdateModelFiles = result.GeneratedSources
            .Where(s => s.FileName.Contains("AddressUpdateModel.g.cs"));
        
        nestedUpdateModelFiles.Should().BeEmpty(
            "should not generate nested UpdateModel when [DynamoDbEntity] is missing");
    }

    [Fact]
    public void Generator_WithNumericPropertiesInNestedType_GeneratesCorrectNullableTypes()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Metrics
    {
        [DynamoDbAttribute(""score"")]
        public int Score { get; set; }
        
        [DynamoDbAttribute(""rating"")]
        public decimal Rating { get; set; }
        
        [DynamoDbAttribute(""count"")]
        public long Count { get; set; }
    }

    [DynamoDbTable(""items"")]
    public partial class Item
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""metrics"")]
        public Metrics Metrics { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        var metricsUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("MetricsUpdateModel.g.cs"));
        
        metricsUpdateModelFile.Should().NotBeNull("should generate MetricsUpdateModel class");
        
        var code = metricsUpdateModelFile!.SourceText.ToString();
        
        // Verify numeric types are made nullable
        code.Should().Contain("int? Score", "should generate nullable int for Score property");
        code.Should().Contain("decimal? Rating", "should generate nullable decimal for Rating property");
        code.Should().Contain("long? Count", "should generate nullable long for Count property");
    }

    [Fact]
    public void Generator_WithCollectionPropertiesInNestedType_GeneratesCorrectTypes()
    {
        // Arrange
        var source = @"
using System;
using System.Collections.Generic;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Settings
    {
        [DynamoDbAttribute(""tags"")]
        public List<string> Tags { get; set; } = new();
        
        [DynamoDbAttribute(""categories"")]
        public HashSet<string> Categories { get; set; } = new();
    }

    [DynamoDbTable(""items"")]
    public partial class Item
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""settings"")]
        public Settings Settings { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        var settingsUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("SettingsUpdateModel.g.cs"));
        
        settingsUpdateModelFile.Should().NotBeNull("should generate SettingsUpdateModel class");
        
        var code = settingsUpdateModelFile!.SourceText.ToString();
        
        // Verify collection types are made nullable
        code.Should().Contain("List<string>?", "should generate nullable List for Tags property");
        code.Should().Contain("HashSet<string>?", "should generate nullable HashSet for Categories property");
    }

    [Fact]
    public void Generator_WithDifferentNamespaces_PreservesNamespace()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace MyApp.Domain.ValueObjects
{
    [DynamoDbEntity]
    public partial class Address
    {
        [DynamoDbAttribute(""city"")]
        public string City { get; set; } = string.Empty;
    }
}

namespace MyApp.Domain.Entities
{
    using MyApp.Domain.ValueObjects;

    [DynamoDbTable(""customers"")]
    public partial class Customer
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""address"")]
        public Address ShippingAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        var addressUpdateModelFile = result.GeneratedSources
            .FirstOrDefault(s => s.FileName.Contains("AddressUpdateModel.g.cs"));
        
        addressUpdateModelFile.Should().NotBeNull("should generate AddressUpdateModel class");
        
        var code = addressUpdateModelFile!.SourceText.ToString();
        
        // Verify namespace is preserved from the nested type
        code.Should().Contain("namespace MyApp.Domain.ValueObjects",
            "should preserve original namespace of nested type");
    }

    [Fact]
    public void Generator_WithMultipleEntitiesUsingSameNestedType_GeneratesOnlyOneNestedUpdateModel()
    {
        // Arrange
        var source = @"
using System;
using Oproto.FluentDynamoDb.Attributes;

namespace TestNamespace
{
    [DynamoDbEntity]
    public partial class Address
    {
        [DynamoDbAttribute(""city"")]
        public string City { get; set; } = string.Empty;
    }

    [DynamoDbTable(""customers"")]
    public partial class Customer
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""address"")]
        public Address ShippingAddress { get; set; } = new();
    }

    [DynamoDbTable(""orders"")]
    public partial class Order
    {
        [PartitionKey]
        [DynamoDbAttribute(""pk"")]
        public string Id { get; set; } = string.Empty;
        
        [DynamoDbMap]
        [DynamoDbAttribute(""deliveryAddress"")]
        public Address DeliveryAddress { get; set; } = new();
    }
}";

        // Act
        var result = GenerateCode(source);

        // Assert
        result.Diagnostics.Should().NotContain(d => d.Severity == DiagnosticSeverity.Error);
        
        // Verify only one AddressUpdateModel is generated
        var addressUpdateModelFiles = result.GeneratedSources
            .Where(s => s.FileName.Contains("AddressUpdateModel.g.cs"))
            .ToList();
        
        addressUpdateModelFiles.Should().HaveCount(1,
            "should generate only one AddressUpdateModel even when used by multiple entities");
    }

    private static GeneratorTestResult GenerateCode(string source)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] {
                CSharpSyntaxTree.ParseText(source),
                CSharpSyntaxTree.ParseText("[assembly: Oproto.FluentDynamoDb.Attributes.FluentDynamoDbSchemaVersion(1, 0)]")
            },
            TestHelpers.DynamicCompilationHelper.GetFluentDynamoDbReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new DynamoDbSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        var generatedSources = outputCompilation.SyntaxTrees
            .Skip(compilation.SyntaxTrees.Count())
            .Select(tree => new GeneratedSource(tree.FilePath, tree.GetText()))
            .ToArray();

        return new GeneratorTestResult
        {
            Diagnostics = diagnostics,
            GeneratedSources = generatedSources
        };
    }
}
