using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb.Storage;

namespace InvoiceManager.Entities;

/// <summary>
/// Table class for managing customers, invoices, and invoice lines in DynamoDB.
/// 
/// This class demonstrates single-table design where multiple entity types share
/// the same table, using hierarchical composite keys to enable efficient access patterns.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Key Design:</strong>
/// </para>
/// <para>
/// All entities use the same partition key format "CUSTOMER#{customerId}" to group
/// all data for a customer together. The sort key distinguishes entity types:
/// </para>
/// <list type="bullet">
/// <item><description>Customer: sk = "PROFILE"</description></item>
/// <item><description>Invoice: sk = "INVOICE#{invoiceNumber}"</description></item>
/// <item><description>InvoiceLine: sk = "INVOICE#{invoiceNumber}#LINE#{lineNumber}"</description></item>
/// </list>
/// <para>
/// <strong>Access Patterns:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Get customer profile: Query pk = "CUSTOMER#{id}", sk = "PROFILE"</description></item>
/// <item><description>Get complete invoice with lines: Query pk = "CUSTOMER#{id}", sk begins_with "INVOICE#{num}"</description></item>
/// <item><description>List customer invoices: Query pk = "CUSTOMER#{id}", sk begins_with "INVOICE#"</description></item>
/// </list>
/// <para>
/// <strong>Why Single-Table Design?</strong>
/// </para>
/// <para>
/// Single-table design enables fetching related data in a single query, reducing
/// latency and cost. It also enables atomic transactions across entity types.
/// </para>
/// </remarks>
public partial class InvoicesTable : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for invoices.
    /// </summary>
    public const string TableName = "invoices";

    /// <summary>
    /// Initializes a new instance of the InvoicesTable class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public InvoicesTable(IAmazonDynamoDB client) : this(client, TableName)
    {
    }

    // Entity accessors (Customers, Invoices, InvoiceLines) are generated by the source generator
    // based on the [GenerateEntityProperty] attributes on Customer, Invoice, and InvoiceLine entities.
}
