using Amazon.DynamoDBv2;
using Oproto.FluentDynamoDb.Storage;

namespace TodoList.Entities;

/// <summary>
/// Table class for managing todo items in DynamoDB.
/// 
/// This class demonstrates the scannable table pattern, which is appropriate for
/// small datasets like personal todo lists. The <see cref="TodoItem"/> entity is
/// marked with [Scannable], enabling full table scans for listing all items.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Access Patterns:</strong>
/// </para>
/// <list type="bullet">
/// <item><description>Add a new todo item (Put operation)</description></item>
/// <item><description>Get all todo items (Scan operation - appropriate for small datasets)</description></item>
/// <item><description>Mark a todo item as complete (Update operation)</description></item>
/// <item><description>Edit a todo item description (Update operation)</description></item>
/// <item><description>Delete a todo item (Delete operation)</description></item>
/// </list>
/// <para>
/// <strong>Why Scannable?</strong>
/// </para>
/// <para>
/// Todo lists are typically small (tens to hundreds of items), making scan operations
/// acceptable. For larger datasets, consider using Query operations with a partition key
/// design (e.g., pk="USER#{userId}") to efficiently retrieve items for a specific user.
/// </para>
/// </remarks>
public partial class TodoItemsTable : DynamoDbTableBase
{
    /// <summary>
    /// The name of the DynamoDB table for todo items.
    /// </summary>
    public const string TableName = "todo-items";

    /// <summary>
    /// Initializes a new instance of the TodoItemsTable class.
    /// </summary>
    /// <param name="client">The DynamoDB client.</param>
    public TodoItemsTable(IAmazonDynamoDB client) : this(client, TableName)
    {
    }

    // Entity accessor (TodoItems) is generated by the source generator
    // based on the [GenerateEntityProperty] attribute on TodoItem entity.
}
